/**        __  _________  _________  _________ /\
 *      __/\_\/\  _____ \/\  _____ \/\   _____\  \
 *     / /:/ /\:\ \___/\ \:\ \___/\ \:\  \___/_   \
 *    / /:/ / _\:\ \  \:\ \:\ \  \:\ \:\_____  \   \
 *   / /:/ / /\ \:\ \  \:\ \:\ \  \:\ \/___/:\  \   \
 *   \ \:\ \//\\ \:\ \__\:\ \:\ \__\:\ \  _\_:\  \   \
 *    \ \:\//_/\\_\:\________\:\________\/\_______\   \   
 *     \ \:\  \//  \/________/\/________/\/_______/   /
 *      \ \:\ //  / GOOS - GO Operating System       /
 *       \ \://  /   c.2006 Andrew F. Hart          /
 *        \_\/__/__________________________________/
 * 
 * ======================================================================
 *  Name: idt.c
 *  External: idt.o
 *  Author: Andrew F. Hart
 *  Date: 2006.05.14
 * =======================================================================
 */
#include <system.h>

/*
 * Purpose of this file:
 * This file provides the implementation of Interrupt Service Routines
 * (ISRs). The full implementation employs a mix of assembly level
 * code (to save the state of the processor at the time of the interrupt)
 * and C-level code (to process the interrupt itself). The assembly-level
 * counterpart to this file is defined in (/krnl/gkstart.asm). The 
 * invocation of the handler routines defined here depends on the contents 
 * of the Interrupt Descriptor Table (IDT) defined in (/krnl/core/idt.c).
 *
 * The First 32 Exceptions:
 * (These exceptions can be generated by the processor and therefore must
 *  be handled. There is room in the IDT (/krnl/core/idt.c) for 256 entries
 *  in all.)   
 * (Some exceptions push onto the stack an error code specific to the
 *  exception caused)
 * (Table comes from [1] (/resources/references.txt))
 * #	Description				Error Code
 * 0	Division By Zero Exception		No
 * 1	Debug Exception				No
 * 2	Non Maskable Interrupt Exception	No
 * 3	Breakpoint Exception			No
 * 4	Into Detected Overflow Exception	No
 * 5	Out of Bounds Exception			No
 * 6	Invalid Opcode Exception		No
 * 7	No Coprocessor Exception		No
 * 8 	Double Fault Exception			Yes
 * 9 	Coprocessor Segment Overrun Exception	No
 * 10	Bad TSS Exception			Yes
 * 11	Segment Not Present Exception		Yes
 * 12	Stack Fault Exception			Yes
 * 13	General Protection Fault Exception	Yes
 * 14	Page Fault Exception			Yes
 * 15	Unknown Interrupt Exception		No
 * 16	Coprocessor Fault Exception		No
 * 17	Alignment Check Exception (486+)	No
 * 18	Machine Check Exception (Pentium/586+)	No
 * 19-31Reserved Exceptions			No
 *
 *
*/

/* Installation of Interrupt Service Routines
 *
 * uses idt_set_gate defined in (/krnl/core/idt.c) with
 * the following parameters:
 * 
 * idt_set_gate(isr_num,handler,0x08,0x8E)
 * isr_num......: the number of the current interrupt
 * handler......: the routine to call to handle the current interrupt
 * 0x08.........: [00001000]: Kernel data segment (/krnl/core/gdt.c)
 * 0x8E.........: [10001110]: Access Flags:
 *                                          - Entry is present
 *                                          - Running in ring 0 (krnl level)
 *                                          - lower bits set to 14h
 *
 *
*/
void isrs_install()
{
  idt_set_gate(0, (unsigned)isr0, 0x08, 0x8E);
  idt_set_gate(1, (unsigned)isr1, 0x08, 0x8E);
  idt_set_gate(2, (unsigned)isr2, 0x08, 0x8E);
  idt_set_gate(3, (unsigned)isr3, 0x08, 0x8E);
  idt_set_gate(4, (unsigned)isr4, 0x08, 0x8E);
  idt_set_gate(5, (unsigned)isr5, 0x08, 0x8E);
  idt_set_gate(6, (unsigned)isr6, 0x08, 0x8E);
  idt_set_gate(7, (unsigned)isr7, 0x08, 0x8E);
  idt_set_gate(8, (unsigned)isr8, 0x08, 0x8E);
  idt_set_gate(9, (unsigned)isr9, 0x08, 0x8E);
  idt_set_gate(10, (unsigned)isr10, 0x08, 0x8E);
  idt_set_gate(11, (unsigned)isr11, 0x08, 0x8E);
  idt_set_gate(12, (unsigned)isr12, 0x08, 0x8E);
  idt_set_gate(13, (unsigned)isr13, 0x08, 0x8E);
  idt_set_gate(14, (unsigned)isr14, 0x08, 0x8E);
  idt_set_gate(15, (unsigned)isr15, 0x08, 0x8E);
  idt_set_gate(16, (unsigned)isr16, 0x08, 0x8E);
  idt_set_gate(17, (unsigned)isr17, 0x08, 0x8E);
  idt_set_gate(18, (unsigned)isr18, 0x08, 0x8E);
  idt_set_gate(19, (unsigned)isr19, 0x08, 0x8E);
  idt_set_gate(20, (unsigned)isr20, 0x08, 0x8E);
  idt_set_gate(21, (unsigned)isr21, 0x08, 0x8E);
  idt_set_gate(22, (unsigned)isr22, 0x08, 0x8E);
  idt_set_gate(23, (unsigned)isr23, 0x08, 0x8E);
  idt_set_gate(24, (unsigned)isr24, 0x08, 0x8E);
  idt_set_gate(25, (unsigned)isr25, 0x08, 0x8E);
  idt_set_gate(26, (unsigned)isr26, 0x08, 0x8E);
  idt_set_gate(27, (unsigned)isr27, 0x08, 0x8E);
  idt_set_gate(28, (unsigned)isr28, 0x08, 0x8E);
  idt_set_gate(29, (unsigned)isr29, 0x08, 0x8E);
  idt_set_gate(30, (unsigned)isr30, 0x08, 0x8E);
  idt_set_gate(31, (unsigned)isr31, 0x08, 0x8E);
}

/* String array to provide textual hints about the current
 * exception
*/
char* exception_messages[] = 
{
  "Divide By Zero Exception",
  "Debug Exception",
  "Non Maskable Interrupt Exception",
  "Breakpoint Exception",
  "Into Detected Overflow Exception",
  "Out of Bounds Exception",
  "Invalid Opcode Exception",
  "No Coprocessor Exception",
  "Double Fault Exception",
  "Coprocessor Segment Overrun Exception",
  "Bad TSS Exception",
  "Segment Not Present Exception",
  "Stack Fault Exception",
  "General Protection Fault Exception",
  "Page Fault Exception",
  "Unknown Interrupt Exception",
  "Coprocessor Fault Exception",
  "Alignment Check Exception (486+)",
  "Machine Check Exception (Pentium/586+)",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved",
  "Reserved"
};

/* The fault handler itself. All of the exception routines
 * eventually pass control to this function after saving 
 * the processor state. 
*/
void isr_fault_handler(struct regs *r)
{
  char errno[20];
  itoa(r->int_no,errno,20);
  if(r->int_no < 32)
  {
    /* Display Interrupt Description and Loop Endlessly */
    putsp("\n[krnl]: ","FLAGRANT ERROR! (");
    putsp(errno," - ");
    puts(exception_messages[r->int_no]);
    puts(") Computer Over.\n");
    dump_cpu();
    for(;;);
  }
}



